#!/usr/bin/env ruby
class DockerSwarm
  %w[ yaml shellwords open3 zlib ].each{|lib| require lib }

  VERSION             = '2.2.1'
  CMD                 = File.basename __FILE__
  DEFAULT_CMD_ARGS    = 'bash -il'
  DEFAULT_DOCKER_ARGS = ''

  CMD_ALIASES = {
    'context'  => %w[ c ],
    'ssh'      => %w[   ],
    'ls'       => %w[   ],
    'services' => %w[ lss ],
    'inspect'  => %w[ i ],
    'logs'     => %w[ l ],
    'restart'  => %w[ r ],
    'update'   => %w[ u ],
    'scale'    => %w[ s ],
    'top'      => %w[ t ],
    'dtop'     => %w[   ],
    'exec'     => %w[ e ],
    'run'      => %w[   ],
    'dive'     => %w[   ],
    'rm'       => %w[   ],
    'ps'       => %w[   ],
    'build'    => %w[ b ],
    'push'     => %w[ P ],
    'pull'     => %w[ p ],
    'deploy'   => %w[ d ],
    'login'    => %w[   ],
    'images'   => %w[ lsi ],
    'rm-image' => %w[ rmi ],
    'clean'    => %w[ clear ],
  }

  def get_cmd_alias(cmd) = CMD_ALIASES.detect{|long, shorts| long == cmd || shorts.include?(cmd) }&.[](0)

  def initialize(argv)
    @argv      = argv.dup
    @env       = {}
    @conf_path = nil
    @cmd       = get_cmd_alias @argv.shift
    @is_quiet  = get_flag %w[ -q --quiet ]
    @image_config = {}

    # autoload environment from `.dockerswarm` YAML config file
    dir = File.expand_path Dir.pwd
    loop do
      conf_path = File.join(dir, '.dockerswarm')
      env = YAML.unsafe_load_file conf_path rescue nil

      if env.is_a?(Hash)
        @image_config = env.delete('build_config') || {}

        unless @is_quiet
          print "⬡ #{@cmd || :help}   "
          env.each do |k, v|
            ENV[k] = v.to_s
            print "⬢ #{k.sub 'DOCKER_', ''} #{v}   "
          end; puts ''
        end

        @conf_path, @env = conf_path, env
        break
      else
        parent_dir = File.expand_path File.join(dir, '..')
        if parent_dir == dir
          STDERR.puts "⬡ no .dockerswarm file found\n\n"
          break
        end
        dir = parent_dir
      end
    end
  end # initialize

  def run
    case @cmd # main action - https://docs.docker.com/reference/cli/docker/
      # ------------------------------------------------------------------------
      when 'context' # https://docs.docker.com/engine/manage-resources/contexts/
        case @argv[0]
          when 'ls' then pexec "docker context ls"
          when 'add'
            die "missing arguments" if @argv.size < 3
            pexec %Q|docker context create #{@argv[1].shellescape} --docker host=ssh://#{@argv[2].shellescape}|
          when 'rm'
            die "missing arguments" if @argv.size < 2
            pexec %Q|docker context rm #{@argv[1].shellescape}|
          when 'env'
            contesti = `docker context ls --format '{{.Name}}'`.split("\n")
            die "context [#{@argv[1]}] not found" unless contesti.include?(@argv[1])

            case @argv[2]
              when 'fish'
                puts %Q|set -gx DOCKER_CONTEXT "#{@argv[1]}";|
                puts %Q|# eval (#{CMD} context env #{@argv[1]} fish --quiet)|
              when 'cmd'
                puts %Q|SET DOCKER_CONTEXT=#{@argv[1]}|
                puts %Q|REM @FOR /f "tokens=*" %i IN ('#{CMD} context env #{@argv[1]} cmd --quiet') DO @%i|
              when 'powershell'
                puts %Q|$Env:DOCKER_CONTEXT = "#{@argv[1]}"|
                puts %Q[# & #{CMD} context env #{@argv[1]} powershell --quiet | Invoke-Expression]
              else
                puts %Q|export  DOCKER_CONTEXT="#{@argv[1]}"|
                puts %Q|# eval $(#{CMD} context env #{@argv[1]} --quiet)|
            end
          when 'unset'
            case @argv[1]
              when 'fish'
                puts %Q|set -e DOCKER_CONTEXT;|
                puts %Q|# eval (#{CMD} context unset fish --quiet)|
              when 'cmd'
                puts %Q|SET DOCKER_CONTEXT=|
                puts %Q|REM   @FOR /f "tokens=*" %i IN ('./#{CMD} context unset cmd --quiet') DO @%i|
              when 'powershell'
                puts %Q|Remove-Item Env:\\DOCKER_CONTEXT|
                puts %Q[# & ./#{CMD} context unset powershell --quiet | Invoke-Expression]
              else
                puts %Q|unset  DOCKER_CONTEXT|
                puts %Q|# eval $(#{CMD} context unset --quiet)|
            end
          else
            die "no subcommand given"
        end
      # ------------------------------------------------------------------------
      when 'ssh'
        die "DOCKER_CONTEXT env undefined" unless ENV['DOCKER_CONTEXT']

        ssh_uri = `docker context inspect --format '{{.Endpoints.docker.Host}}' #{ENV['DOCKER_CONTEXT']}`.strip.sub('ssh://', '')
        host, port = ssh_uri.split ':'
        port ||= 22
        cmd = @argv.map{|i| i.shellescape }.join(' ')

        pexec "ssh -p #{port} #{host} #{cmd}"
      # ------------------------------------------------------------------------
      when 'ls'
        fmt = "--format '{{.Name}}'" if get_flag(%w[ -s --simple ])
        pexec "docker stack ls #{fmt}"
      # ------------------------------------------------------------------------
      when 'services'
        show_full = get_flag %w[ -f --full ]

        if show_full
          list = `docker service ls`.split("\n")
          puts list.shift
        else
          list = `docker service ls --format 'table {{.Name}}\t@ {{.Image}}'`.split("\n").sort
        end

        if stack_name
          list. # filter by stack_name and remove prefix from service name
            select!{|i| i.include? "#{stack_name}_" }.
            map!{|i| i.sub /^#{stack_name}_/, '' }
        end

        puts list
      # ------------------------------------------------------------------------
      when 'inspect'
        is_pretty = get_flag(%w[ -p --pretty ])
        pexec "docker service inspect #{service_name} #{'--pretty' if is_pretty}"
      # ------------------------------------------------------------------------
      when 'logs'
        if get_flag(%w[ -s --save ])
          cmd = "docker service logs --timestamps #{service_name}"
          psystem cmd, run: false
          
          stdout, stderr, status = Open3.capture3 cmd
          gzip_write "#{service_name}.log.gz", stdout
          gzip_write "#{service_name}.err.gz", stderr if stderr.to_s[0]
          
          puts "saved to #{service_name}.{log,err}.gz"
        else
          is_follow = get_flag(%w[ -f --follow ])
          pexec "docker service logs --timestamps #{service_name} #{'-f' if is_follow}"
        end
      # ------------------------------------------------------------------------
      when 'restart'
        pexec "docker service update --force #{service_name}"
      # ------------------------------------------------------------------------
      when 'update'
        # get the image name for this service
        srv, img = %x[
          docker service ls \
            --format '{{.Name}}|{{.Image}}' \
            --filter NAME=#{service_name}
        ].strip.split('|')

        if srv && img
          registry_login

          img = img ? File.basename(img.to_s).split(':').first.to_s : :no_image
          img = "#{img}:#{@argv[1] || :latest}"
          pexec "docker service update --with-registry-auth --image #{ENV['DOCKER_REGISTRY']}/#{img} #{srv}"
        else
          die "no service or image found"
        end
      # ------------------------------------------------------------------------
      when 'scale'
        is_forced = get_flag %w[ -f --force ]

        unless is_forced
          print "Scale `#{service_name}` to `#{@argv[1].to_i}` instances? [y|N] "
          exit if STDIN.gets.strip != 'y'
        end

        pexec "docker service scale #{service_name}=#{@argv[1].to_i}"
      # ------------------------------------------------------------------------
      when 'top'
        id = container_id
        pexec "docker top #{id}" if id
      # ------------------------------------------------------------------------
      when 'exec'
        if id = container_id
          @argv.shift # discard service name

          cmd_args, docker_args = split_args
          pexec "docker exec -ti #{docker_args} #{id} #{cmd_args}"
        end
      # ------------------------------------------------------------------------
      when 'run'
        image = image_name @argv.shift
        cmd_args, docker_args = split_args
        tmp_name = "#{CMD}_#{rand(1_000_000).to_s.rjust 6, '0'}"
        pexec "docker run --rm -ti --name #{tmp_name} --entrypoint '' #{docker_args} #{image} #{cmd_args}"
      # ------------------------------------------------------------------------
      when 'dive'
        image = @argv.first.to_s.include?('/') ? @argv.first : image_name(@argv.first)
        tmp_name = "#{CMD}_dive_#{rand(1_000_000).to_s.rjust 6, '0'}"
        opts = "--rm -ti --name #{tmp_name} -v /var/run/docker.sock:/var/run/docker.sock"
        pexec "docker run #{opts} wagoodman/dive:latest #{image}"
      when 'dtop'
        tmp_name = "#{CMD}_dtop_#{rand(1_000_000).to_s.rjust 6, '0'}"
        opts = "--rm -ti --name #{tmp_name} -v /var/run/docker.sock:/var/run/docker.sock"
        pexec "docker run #{opts} amir20/dtop:latest"
      # ------------------------------------------------------------------------
      when 'rm'
        is_forced = get_flag %w[ -f --force ]

        die "missing stack name" unless stack_name

        unless is_forced
          print "Remove `#{stack_name}`? [y|N] "
          exit if STDIN.gets.strip != 'y'
        end

        pexec "docker stack rm #{stack_name}"
      # ------------------------------------------------------------------------
      when 'ps'
        show_containers = get_flag %w[ -c --containers ]
        show_stats      = get_flag %w[ -s --stats ]

        die "missing stack name" unless stack_name

        output = []

        header = %w[ Name Image ID Node CurrentState DesiredState Error ]
        cmd = "docker stack ps #{stack_name} --no-trunc --format '#{ header.map{|k| %Q|{{.#{k}}}| }.join('\t') }'"
        tmp = psystem(cmd, capture: true, blank: false)
        tmp.gsub! /@sha256:(....)[a-z0-9]+/, ' \1'  #/
        lines = csv2table(tmp, header: header, tag: 'SERVICES')

        header = lines.shift
        lines.sort!
        output << header
        output << lines.grep(/Running/).join("\n")

        lines = lines.grep_v(/Running/)
        output += lines.map do |l|
          l.sub!(/^([^ ]+)( .+)/){ "\033[0;30;41m#{$1}\033[0m#{$2}" }
        end

        if show_containers
          output << ''
          header = %w[ Names Image ID Status Ports ]
          cmd = "docker container ls --filter label=com.docker.stack.namespace=#{stack_name} --format '#{ header.map{|k| %Q|{{.#{k}}}| }.join('\t') }'"
          tmp = psystem(cmd, capture: true, blank: false).
            gsub('0.0.0.0', '*').gsub('[::]', '*').
            gsub(/(\.\d+)\.(\p{Alnum}{12})(\p{Alnum}{13})/, '\1 \2').sub(/NAMES {13}/, 'NAMES').
            gsub(/(.+\s(\d+.[tu][cd]p).*)/){|m| m.gsub(/->\d+(.tcp)*/,'').split(', ').uniq.join ',' }.strip
          lines = csv2table(tmp, header: header, tag: 'CONTAINERS')
          output << lines.shift
          output << lines.sort.join("\n")
        end

        if show_stats
          output << ''
          header = %w[ Name MemUsage CPUPerc ]
          cmd = "docker stats --all --no-stream --format '#{ header.map{|k| %Q|{{.#{k}}}| }.join('\t') }'"
          tmp = psystem(cmd, capture: true).gsub(/(\.\d+)\.(\p{Alnum}{25})/, "\\1\t\\2")
          tmp = tmp.split("\n").grep(/#{ENV['DOCKER_STACK']}_/).join("\n") if ENV['DOCKER_STACK']
          lines = csv2table(tmp, header: header.insert(1, 'ID'), tag: 'MEM/CPU')
          lines = lines.grep_v(/0B \/ 0B\s+0.00%/).grep_v(/-- \/ --/)
          output << lines.shift
          output << lines.sort.join("\n")
        end

        output = output.join "\n"
        
        puts output
      # ------------------------------------------------------------------------
      when 'login'
        die "DOCKER_REGISTRY env undefined" unless ENV['DOCKER_REGISTRY']
        psystem "docker login #{registry_domain}"
      # ------------------------------------------------------------------------
      when 'images'
        lines = `docker image ls 2> /dev/null`.split("\n")
        puts lines.shift
        puts ENV['DOCKER_REGISTRY'] \
          ? lines.select{|l| l.include? ENV['DOCKER_REGISTRY'] }
          : lines
      # ------------------------------------------------------------------------
      when 'rm-image'
        images = @argv.map{|i| i.shellescape }.join ' '
        pexec "docker image rm #{images}"
      # ------------------------------------------------------------------------
      when 'build'
        name, tag = @argv[0].to_s.chomp(File::SEPARATOR).split(':')
        tag ||= :latest  # default tag
        folder = @argv[1] || name

        Dir.chdir(folder) do
          c = parse_image_config
          c['tags'] << "#{name}:#{tag}"

          system c['pre_cmd'] if c['pre_cmd']

          psystem [
            'docker build',
            c['build-args'].map{|k,v| "--build-arg #{k.shellescape}=#{v.to_s.shellescape}" },
            c['tags'].map{|i| "-t #{image_name(i).shellescape}"},
            ("-f #{c['file'].shellescape}" if c['file']),
            c['context']
          ].flatten.compact.join(' ')

          system c['post_cmd'] if c['post_cmd']
        end
      # ------------------------------------------------------------------------
      when 'push'
        die "DOCKER_REGISTRY env undefined" unless ENV['DOCKER_REGISTRY']
        die "no image specified" if @argv.size == 0

        ids  = image_ids_read
        logged_in = false

        while name = @argv.shift
          name, tag = name.to_s.chomp(File::SEPARATOR).split(':')
          tag ||= :latest
          name = image_name "#{name}:#{tag}"

          old_id = ids[name]
          new_id = `docker image ls --format "{{.ID}}" #{name}`.strip

          if old_id != new_id
            unless logged_in
              registry_login
              logged_in = true
            end
            puts ''
            psystem "docker image push #{name.shellescape}" if $?.to_i == 0
            image_ids_update(ids.merge! name => new_id)    if $?.to_i == 0
          else
            puts "NOTE: image already pushed - #{new_id} / #{File.basename name}\n\n"
          end
        end
      # ------------------------------------------------------------------------
      when 'pull'
        registry_login

        if name = @argv[0]
          name, tag = name.to_s.chomp(File::SEPARATOR).split(':')
          tag ||= :latest
          name = image_name "#{name}:#{tag}"

          pexec "docker image pull #{name.shellescape}"
        else
          puts "pulling all previously pushed images..."
          images_pushed  = image_ids_read
          images_current = `docker image ls --format "{{.Repository}}:{{.Tag}}|{{.ID}}"`.
            split("\n").select{|l| l.include? ENV['DOCKER_REGISTRY'] }.
            inject({}){|h, l| k, v = l.split('|'); h.merge k => v }

          images_pushed.each do |name, id|
            next if id != images_current[name]
            puts "\n===> #{name}"
            psystem "docker image pull #{name.shellescape}"
          end
        end
      # ------------------------------------------------------------------------
      when 'clean'
        psystem "docker container prune -f"
        psystem "docker image     prune -f"
        psystem "docker buildx    prune -f" if @argv.include?('-c') || @argv.include?('--cache')
      # ------------------------------------------------------------------------
      when 'deploy'
        run_in_fg = get_flag %w[ -f --foreground ]
        hook_present = File.exist?('dswarm-deploy.hook')

        psystem "dswarm-deploy.hook pre " if hook_present

        name = stack_name

        conf_names = [@argv[1], "#{name}.yml", "compose.yml", "docker-compose.yml"].compact
        conf = conf_names.detect{|f| File.exist? f }
        die "compose file not found (#{conf_names.join '|'})" unless conf

        # NOTE: docker swarm only supports "file:" key and not "environment:" one!
        env, env_file = {}, "#{File.basename conf, File.extname(conf)}.env"
        
        if File.exist?(env_file)
          env = YAML.unsafe_load_file env_file rescue {}
          env.each do |k, v|
            ENV[k.to_s] = v.to_s
            File.write("#{k}.env", v)
          end
        end

        psystem "docker stack deploy --detach=#{!run_in_fg} --with-registry-auth --prune -c #{conf.shellescape} #{name.shellescape}"

        if File.exist?(env_file)
          env.each{|k, v| File.unlink("#{k}.env") if File.exist?("#{k}.env") }
        end

        psystem "dswarm-deploy.hook post" if hook_present
      # ------------------------------------------------------------------------
      else
        puts <<~TXT
          USAGE: #{CMD} <action> [params] [-q|--quiet]

          ### STACK actions
            <d|deploy>       [stack-name] [compose.yml] [-f|--foreground]
              # if compose.env exists and contains a dictionary of secrets
              # then relative EVN vars and temporary KEY.env files will be
              # created for use with docker secrets
            ls               [-s|--simple]
            ps               [stack-name] [-c|--containers] [-s|--stats]
            rm               [stack-name] [-f|--force]
            <lss|services>   [-f|--full]
            dtop             # interactive log viewer | https://github.com/amir20/dtop

          ### SERVICE actions
            <i|inspect>      <service-id> [-p|--pretty]
            <l|logs>         <service-id> [-f|--follow] [-s|--save]
            <r|restart>      <service-id>
            <u|update>       <service-id> [image-tag]
            <s|scale>        <service-id> <num_instances> [-f]
            <t|top>          <service-id>[.replica]
            <e|exec>         <service-id>[.replica] [command [args]] [-- docker-args]

          ### IMAGE actions
            login            # interactive login to DOCKER_REGISTRY
            <lsi|images>
            <rmi|rm-image>   <image-name:tag> [<image-name:tag> ...]
            <b|build>        <image-name>[:tag] [build-folder]
            <P|push>         <image-name>[:tag] [image-name[:tag] ...]
            <p|pull>         [<image-name>[:tag]]
            <clean|clear>    [-c|--cache]
            run              <image-id>   [command [args]] [-- docker-args]
            dive             <image-id>  # https://github.com/wagoodman/dive

          ### CONTEXT actions
            <c|context>      ls
            <c|context>      add <context-name> <ssh-user@address>
            <c|context>      rm  <context-name>
            <c|context>      env <context_name> [sh|fish|cmd|powershell]
            <c|context>      unset              [sh|fish|cmd|powershell]
            ssh              [remote-command]

          ### `.dockerswarm` YAML keys
            DOCKER_CONTEXT   context name / target machine
            DOCKER_STACK     stack name   / service-id prefix
            DOCKER_REGISTRY  repository base path
        TXT
    end # case - main action
  end # run

  private
    def die(msg, code: 1)
      puts "ERR: #{msg}"
      exit code
    end # die

    def get_flag(flags = %w[])
      found = false

      flags.each do |f|
        next unless @argv.include?(f)

        @argv.delete f
        found = true
      end

      found
    end # get_flag
    
    # print command before calling system()
    def psystem(cmd, run: true, capture: false, call_exec: false, prefix: "RUNNING: ", blank: true)
      print(%Q|⬡ #{prefix}#{cmd}\n#{"\n" if blank}|)
      if run
        capture \
          ? %x[#{cmd}]
          : (call_exec ? exec(cmd) : system(cmd))
      end
    end # psystem
    
    def pexec(cmd, **kwargs) = psystem(cmd, **kwargs, call_exec: true)

    # https://devops.stackexchange.com/questions/12924/how-to-get-the-ids-of-docker-containers-that-belong-to-a-service-given-the-serv/12963#12963
    def container_id
      service, replica = service_name.split '.'
      lines = `docker ps --filter label=com.docker.swarm.service.name=#{service} --format '{{.Names}}\\t{{.ID}}'`.split("\n").sort
      line = replica.to_i > 0 \
        ? lines.detect{|l| l.start_with? "#{service}.#{replica}" }
        : lines.first
      puts %Q|⬡ TARGET: #{line || '--'}|
      line.to_s.split("\s").last
    end # container_id

    def service_name(name=nil) = [ENV['DOCKER_STACK'   ], name || @argv.first || :no_service].compact.join('_')

    def image_name(name=nil)   = [ENV['DOCKER_REGISTRY'], name || @argv.first || :no_image].compact.join('/')

    def stack_name             = @@stack_name ||= (@argv.first || ENV['DOCKER_STACK'] || :no_stack)

    def registry_domain        = ENV['DOCKER_REGISTRY'].to_s.split('/', 2).first || :no_registry

    def registry_login
      die "DOCKER_REGISTRY env undefined" unless ENV['DOCKER_REGISTRY']

      print 'Logging in ... '
      logged_in = system "docker login #{registry_domain}", in: :close, out: '/dev/null', err: [:child, :out]
      puts "#{logged_in ? :SUCCESS : :ERROR}"
      exit 1 unless logged_in
    end # registry_login

    def split_args(default_args1: DEFAULT_CMD_ARGS, default_args2: DEFAULT_DOCKER_ARGS)
      if sep_pos = @argv.index('--')
        args1 = @argv[0...sep_pos  ].map{|i| i.shellescape }.join(' ')
        args2 = @argv[(sep_pos+1)..].map{|i| i.shellescape }.join(' ')
      else
        args1 = @argv.map{|i| i.shellescape }.join(' ')
        args2 = []
      end

      [args1.size > 0 ? args1 : default_args1,
       args2.size > 0 ? args2 : default_args2]
    end # split_args

    def image_ids_read = YAML.unsafe_load_file("#{@conf_path}.image-versions") rescue {}

    def image_ids_update(data) = File.write("#{@conf_path}.image-versions", data.to_yaml)

    def parse_image_config(path = 'dswarm.yml')
      cfg = YAML.unsafe_load_file(path) rescue {}
      cfg = @image_config.merge cfg
      res = cfg.slice 'pre_cmd', 'post_cmd'
      
      def subst_dir(s) = s.gsub('_FOLDER_', File.basename(Dir.pwd))
      
      res['pre_cmd' ] = subst_dir(res['pre_cmd' ]) if res['pre_cmd' ]
      res['post_cmd'] = subst_dir(res['post_cmd']) if res['post_cmd']

      res['context'] = cfg['context'] || '.'
      res['context'] = %x[#{subst_dir cfg['context'][2..]}].strip if cfg['context'].to_s.start_with?('$ ')

      res['file'] = cfg['file']
      res['file'] = %x[#{subst_dir cfg['file'][2..]}].strip if cfg['file'].to_s.start_with?('$ ')

      res['tags'] = cfg['tags'].to_a.map do |t|
        t.start_with?('$ ') ? %x[#{subst_dir t[2..]}].strip : t
      end

      res['build-args'] = cfg['build-args'].to_a.inject({}) do |h, i|
        name, cmd = i.first
        cmd = %x[#{subst_dir cmd[2..]}].strip if cmd.to_s.start_with?('$ ')
        h.merge! name => cmd
      end

      res
    end # parse_image_config

    def gzip_write(fname, content)
      Zlib::GzipWriter.open(fname) do |gz|
        gz.mtime, gz.orig_name = Time.now, fname
        gz.write content
      end
    end # gzip_write
    
    def gzip_read(fname) = Zlib::GzipReader.open(fname){|gz| gz.read }

    def csv2table(content, sep1: "\t", sep2: '  ', header: [], tag: nil)
      if ENV['DOCKER_REGISTRY']
        path = File.dirname(ENV['DOCKER_REGISTRY'])
        content.gsub! path, '®'
      end

      rows = content.split("\n").map{|l| l.split sep1 }
      rows.unshift header.map.with_index{|h,i| "[#{h}]#{' '+tag if i == 0 && tag}" }
      num_columns = rows.map{|r| r.size }.max
      max_length = num_columns.times.map do |i|
        rows.map{|r| r[i].to_s.size }.max
      end

      rows = rows.map{|r| r.map.with_index{|c,i| c.ljust max_length[i] } }

      rows[0].each_with_index do |c,i|
        c.sub!(/^([^ ]+) {0,1}([^ ]+)*( +)*/){ "\033[0;30;46m#{$1}\033[0m \033[4;30;44m#{$2}\033[0m#{$3}" }
      end

      rows.map{|r| r.join(sep2) }
    end # csv2table
end # class DockerSwarm

if $0 == __FILE__ # running as a script
  Process.setproctitle "ruby:#{DockerSwarm::CMD}"
  DockerSwarm.new(ARGV).run
end
